### ISSUE TITLE
Questions on the new strategy

### ISSUE THREAD

**Issue by siddharthkp** [npm-janitor/meta#1]
Copied from (here)[https://github.com/npm-janitor/npm-janitor#the-idea]

```
The idea:

Create a bot that would:

Go throught all the published node modules for a partiuclar user.
Check for validity of their package.json
Raise an issue or send a PR as the user itself not as a bot!

The New strategy:

Get write acess to repos of the user using this.
Using package-json-validator module validate the package.json
Send a PR if needed.
```

> as the user itself not as a bot!

> We don't currently allow bots to create issues, comments, and PRs. - Jamie from Gitub

Does github condemn doing this? What am I missing here? [greenkeeper](http://greenkeeper.io/) seems to be a popular bot that does that. Or was this in the context of private repos?

> Get write access to repos of the user using this.

I have qualms about asking for write permission and impersonating the author. Sounds sketchy.

How I am looking at this project is very similar to how greenkeeper works, you give consent and then greenkeeper will keep an eye on your repository.

**Comment by siddharthkp** [comment]
P.S. You'll have to give write access to this repo for assigning people and labels 😄

**Comment by hemanth** [comment]
Well, this idea was in [Oct 12 2014](https://github.com/npm-janitor/npm-janitor/commit/a97c56a18844cf61dcbf53be23acda81bb90af6b) long back even before greenkeeper was conceptualized ;) 

Heh heh right now you can @/them. 

Update: @siddharthkp: Members will be able to clone, pull, and push all repositories. 😇

**Comment by siddharthkp** [comment]
Ah, didn't see the date!
